### ISSUE TITLE
Initiating USB transceiver connection is hard

### ISSUE THREAD

**Issue by Aeroid** [z8i/ha_custom_klimaloggpro#1]
Generally this works great (Base 30.3039 + 4x30.3181 + 2x30.3144) attached to a Pi. But I found it hard to get the USB connection working. I tried various options from the Home Assistant Host/PI and I wasn't sure if this was because the Base/USB wasn't paired or if the reconnect didn't work correctly. 
Initial workaround: I put the USB transceiver into my windows machine and used the TFA windows software for initial pairing (long press USB Button on base). Then switching the USB transceiver over to the PI, and the Base seemed not to notice the quick signal drop and kept USB connection thereafter.

Few days later I restarted the Base (removed batteries) and USB wouldn't reconnect. What worked then was to short-press USB on the base to start searching the USB transceiver wireless connection and restart Home Assistant also. This re-connected correctly.

I was already digging through the code to find the init section for the USB connection and possibly kickstart this on the Home Assistant console, but couldn't spot it. 

In the end, I think the integration needs a "pair USB tranceiver" and "reconnect USB transceiver" command/button. I wouldn't want to restart Home Assistant each time I change batteries in the base.

Would be great to hear if there is an easier solution.

**Comment by z8i** [comment]
I am not completely sure if the initial setup with the windows tool is needed, but I did it too, because I switched from windows to Home Assistant at some point. 
If I change batteries, I just press the USB-button and it reconnects to Home Assistant right away. Did you try without restarting home assistant?

Regarding battery change:
the original code i forked has some function to set one channel to create an acoustic alert, if the battery is low... this happens anytime the battery gets low... even in the middle of the night... Please be aware. If you dig into the code and see that function, feel free to change it ;-)
